// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.0--rc1
// source: api/msgpusher/v1/msgpusher.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MsgPusherClient is the client API for MsgPusher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgPusherClient interface {
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
	BatchSend(ctx context.Context, in *BatchSendRequest, opts ...grpc.CallOption) (*SendResponse, error)
}

type msgPusherClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgPusherClient(cc grpc.ClientConnInterface) MsgPusherClient {
	return &msgPusherClient{cc}
}

func (c *msgPusherClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, "/api.msgpusher.MsgPusher/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgPusherClient) BatchSend(ctx context.Context, in *BatchSendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, "/api.msgpusher.MsgPusher/BatchSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgPusherServer is the server API for MsgPusher service.
// All implementations must embed UnimplementedMsgPusherServer
// for forward compatibility
type MsgPusherServer interface {
	Send(context.Context, *SendRequest) (*SendResponse, error)
	BatchSend(context.Context, *BatchSendRequest) (*SendResponse, error)
	mustEmbedUnimplementedMsgPusherServer()
}

// UnimplementedMsgPusherServer must be embedded to have forward compatible implementations.
type UnimplementedMsgPusherServer struct {
}

func (UnimplementedMsgPusherServer) Send(context.Context, *SendRequest) (*SendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedMsgPusherServer) BatchSend(context.Context, *BatchSendRequest) (*SendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchSend not implemented")
}
func (UnimplementedMsgPusherServer) mustEmbedUnimplementedMsgPusherServer() {}

// UnsafeMsgPusherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgPusherServer will
// result in compilation errors.
type UnsafeMsgPusherServer interface {
	mustEmbedUnimplementedMsgPusherServer()
}

func RegisterMsgPusherServer(s grpc.ServiceRegistrar, srv MsgPusherServer) {
	s.RegisterService(&MsgPusher_ServiceDesc, srv)
}

func _MsgPusher_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgPusherServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.msgpusher.MsgPusher/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgPusherServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgPusher_BatchSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchSendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgPusherServer).BatchSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.msgpusher.MsgPusher/BatchSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgPusherServer).BatchSend(ctx, req.(*BatchSendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MsgPusher_ServiceDesc is the grpc.ServiceDesc for MsgPusher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MsgPusher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.msgpusher.MsgPusher",
	HandlerType: (*MsgPusherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _MsgPusher_Send_Handler,
		},
		{
			MethodName: "BatchSend",
			Handler:    _MsgPusher_BatchSend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/msgpusher/v1/msgpusher.proto",
}
