service:
  name: mgr
  version: v1
  msgpushermanager:
    endpoint: discovery:///austin-v2.msgpusher.manager.service
    timeout: 30s
trace:
  endpoint: http://127.0.0.1:14268/api/traces
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 30s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/austin-v2?parseTime=true&collation=utf8mb4_unicode_ci&loc=Asia%2FShanghai&charset=utf8mb4
  redis:
    addr: 127.0.0.1:6379
    password: "123456"
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  service_key: "mgr-service-key"
  api_key: "mgr-api-key"
etcd:
  address: 192.168.127.128:2379