service:
  name: austin-v2.adminInterface.service
  version: v1
  administrator:
    endpoint: discovery:///austin-v2.administrator.service
    timeout: 30s
  authorization:
    endpoint: discovery:///austin-v2.authorization.service
    timeout: 30s
  files:
    endpoint: discovery:///austin-v2.files.service
    timeout: 30s
  msgpushermanager:
    endpoint: discovery:///austin-v2.msgpusher.manager.service
    timeout: 30s
trace:
  endpoint: http://127.0.0.1:14268/api/traces
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 5s
data:
  redis:
    addr: "127.0.0.1:6379"
    password: "123456"
    read_timeout: "0.2s"
    write_timeout: "0.2s"
auth:
  service_key: "austin-v2-admin-service-key"
  api_key: "austin-v2-admin-api-key"
  api_key_expire: "86400"

  casbin_source: root:123456@tcp(127.0.0.1:3306)/kratos-admin?parseTime=true&collation=utf8mb4_unicode_ci&loc=Asia%2FShanghai&charset=utf8mb4
  casbin_model: "[request_definition]
  
  r = sub, obj, act
  
  [policy_definition]
  
  p = sub, obj, act
  
  [role_definition]
  
  g = _, _
  
  [policy_effect]
  
  e = some(where (p.eft == allow))
  
  [matchers]
  
  m = g(r.sub, p.sub) && keyMatch2(r.obj, p.obj) && regexMatch(r.act, p.act)"
etcd:
  address: 127.0.0.1:2379
