// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"austin-v2/app/administrator/internal/biz"
	"austin-v2/app/administrator/internal/conf"
	"austin-v2/app/administrator/internal/data"
	"austin-v2/app/administrator/internal/server"
	"austin-v2/app/administrator/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, auth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewMysqlCmd(confData, logger)
	cmdable := data.NewRedisCmd(confData, logger)
	dataData, cleanup, err := data.NewData(db, cmdable, logger)
	if err != nil {
		return nil, nil, err
	}
	administratorRepo := data.NewAdministratorRepo(dataData, logger)
	administratorUseCase := biz.NewAdministratorUseCase(administratorRepo, logger)
	administratorService := service.NewAdministratorService(administratorUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, administratorService, logger)
	registrar := data.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
