// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"austin-v2/app/msgpusher/internal/biz"
	"austin-v2/app/msgpusher/internal/conf"
	"austin-v2/app/msgpusher/internal/data"
	"austin-v2/app/msgpusher/internal/process"
	"austin-v2/app/msgpusher/internal/server"
	"austin-v2/app/msgpusher/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	preParamCheckAction := process.NewPreParamCheckAction()
	assembleAction := process.NewAssembleAction()
	afterParamCheckAction := process.NewAfterParamCheckAction()
	client := data.NewAsynqClient(confData)
	sendMqAction := process.NewSendMqAction(logger, client)
	businessProcess := process.NewBusinessProcess(preParamCheckAction, assembleAction, afterParamCheckAction, sendMqAction)
	db := data.NewMysqlCmd(confData, logger)
	cmdable := data.NewRedisCmd(confData, logger)
	dataData, cleanup, err := data.NewData(confData, logger, db, cmdable)
	if err != nil {
		return nil, nil, err
	}
	iMessageTemplateRepo := data.NewMessageTemplateRepo(dataData, logger)
	messageTemplateUseCase := biz.NewMessageTemplateUseCase(iMessageTemplateRepo, logger)
	msgPusherUseCase := biz.NewMsgPusherUseCase(logger, businessProcess, messageTemplateUseCase)
	msgPusherService := service.NewMsgPusherService(msgPusherUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, msgPusherService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
