service:
  name: austin-v2.msgpusher-worker.service
  version: v1
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/austin-v2?parseTime=true&collation=utf8mb4_unicode_ci&loc=Asia%2FShanghai&charset=utf8mb4
  redis:
    addr: "127.0.0.1:6379"
    password: "123456"
    read_timeout: "0.2s"
    write_timeout: "0.2s"
  mongodb:
      url: "mongodb://localhost:27017"
      username:
      password:

