// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLaSystemAuthMenu = "la_system_auth_menu"

// LaSystemAuthMenu mapped from table <la_system_auth_menu>
type LaSystemAuthMenu struct {
	ID         int32               `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 主键
	Pid        int32               `gorm:"column:pid;not null" json:"pid"`                    // 上级菜单
	MenuType   string              `gorm:"column:menu_type;not null" json:"menu_type"`        // 权限类型: M=目录，C=菜单，A=按钮
	MenuName   string              `gorm:"column:menu_name;not null" json:"menu_name"`        // 菜单名称
	MenuIcon   string              `gorm:"column:menu_icon;not null" json:"menu_icon"`        // 菜单图标
	MenuSort   int32               `gorm:"column:menu_sort;not null" json:"menu_sort"`        // 菜单排序
	Perms      string              `gorm:"column:perms;not null" json:"perms"`                // 权限标识
	Paths      string              `gorm:"column:paths;not null" json:"paths"`                // 路由地址
	Component  string              `gorm:"column:component;not null" json:"component"`        // 前端组件
	Selected   string              `gorm:"column:selected;not null" json:"selected"`          // 选中路径
	Params     string              `gorm:"column:params;not null" json:"params"`              // 路由参数
	IsCache    int32               `gorm:"column:is_cache;not null" json:"is_cache"`          // 是否缓存: 0=否, 1=是
	IsShow     int32               `gorm:"column:is_show;not null;default:1" json:"is_show"`  // 是否显示: 0=否, 1=是
	IsDisable  int32               `gorm:"column:is_disable;not null" json:"is_disable"`      // 是否禁用: 0=否, 1=是
	CreateTime int64               `gorm:"column:create_time;not null" json:"create_time"`    // 创建时间
	UpdateTime int64               `gorm:"column:update_time;not null" json:"update_time"`    // 更新时间
	Children   []*LaSystemAuthMenu `gorm:"-"`
}

// TableName LaSystemAuthMenu's table name
func (*LaSystemAuthMenu) TableName() string {
	return TableNameLaSystemAuthMenu
}
